import type { DesignDNA, DesignSystemId } from "./types";

/* ==========================================================================
   Design DNA profiles.
   Each design system has a genome: layout architecture, spacing density,
   hero construction, nav style, component rules, motion character, and
   typography rules. The canvas obeys the render hints (heroLayout,
   navStyle, density) directly, and both generation phases obey the rules —
   so a Luxury Black site and a Contractor Pro site differ structurally,
   not just in color.
   ========================================================================== */

const DNA: Record<DesignSystemId, DesignDNA> = {
  "luxury-black": {
    id: "luxury-black",
    name: "Luxury Black",
    essence: "Cinematic restraint — the site equivalent of a dark showroom.",
    traits: ["cinematic", "oversized typography", "minimal text", "expensive", "dark surfaces", "slow motion"],
    heroLayout: "oversized",
    navStyle: "minimal-text",
    density: "airy",
    layoutRules: [
      "One idea per viewport — never compete for attention",
      "Asymmetric compositions with extreme negative space",
      "Full-bleed imagery; content floats over darkness",
      "No more than two columns, ever",
    ],
    componentRules: {
      navigation: "Near-invisible: wordmark and two links, letter-spaced, hairline-free",
      hero: "A single oversized serif statement; the subline whispers beneath it",
      cards: "Borderless or single gold hairline; generous internal padding",
      buttons: "Squared, uppercase, letter-spaced; gold on black, never filled loudly",
      forms: "Minimal fields, underline inputs, no boxes",
    },
    motionRules: {
      character: "Slow, weighted, deliberate — nothing bounces",
      speed: "slow",
      rules: ["800ms+ fades", "Subtle parallax on imagery", "No hover scale above 1.02"],
    },
    typographyRules: {
      display: "High-contrast serif, oversized, tight leading",
      body: "Quiet grotesque at small sizes, generous line-height",
      scale: "Extreme — display 5–7x body size",
      rules: ["Few words, large", "Uppercase micro-labels with wide tracking"],
    },
    imagery: "Macro detail shots, dramatic side-lighting, deep shadows",
    copyDirection: "Say less. Every sentence costs something.",
  },

  "vision-pro": {
    id: "vision-pro",
    name: "Apple Vision Pro",
    essence: "Spatial glass — panels floating in soft volumetric light.",
    traits: ["glass", "depth", "lighting", "floating panels"],
    heroLayout: "centered",
    navStyle: "glass-pill",
    density: "airy",
    layoutRules: [
      "Content lives on floating glass panels, never flush to the page",
      "Soft depth stacking: background, midground panel, foreground control",
      "Massive rounded corners (24–32px)",
      "Light source from above; every panel catches an edge highlight",
    ],
    componentRules: {
      navigation: "Floating frosted pill, detached from the top edge",
      hero: "Centered statement under a soft spotlight; panels orbit beneath",
      cards: "Heavy-blur glass with inner edge-light and deep soft shadows",
      buttons: "Fully rounded, frosted or softly filled — never hard edges",
      forms: "Glass wells with glowing focus rings",
    },
    motionRules: {
      character: "Weightless drift — things float, settle, and breathe",
      speed: "calm",
      rules: ["Panels rise into place", "Blur transitions", "Gentle perpetual float on accents"],
    },
    typographyRules: {
      display: "Refined grotesque, medium weight, tight tracking",
      body: "Same family, lighter, high legibility on translucency",
      scale: "Moderate — clarity over drama",
      rules: ["White at varying opacities, never gray hex values"],
    },
    imagery: "Soft-lit product-style photography with depth of field",
    copyDirection: "Calm, precise, quietly confident.",
  },

  linear: {
    id: "linear",
    name: "Linear",
    essence: "Engineered calm — precision as a brand value.",
    traits: ["precise", "dark", "systematic", "quiet"],
    heroLayout: "centered",
    navStyle: "hairline",
    density: "balanced",
    layoutRules: [
      "Strict vertical rhythm; every gap from a 4px scale",
      "Single accent color used surgically",
      "Hairline borders carry the structure, not backgrounds",
      "Text-first sections with rare, purposeful illustration",
    ],
    componentRules: {
      navigation: "Slim hairline bar, compact text links",
      hero: "Medium-weight headline, one accent gradient word at most",
      cards: "Near-flat panels, 1px borders, no shadow theatrics",
      buttons: "Small, dense, rounded-lg; keyboard-shortcut energy",
      forms: "Compact, monospace placeholders",
    },
    motionRules: {
      character: "Instant and exact — motion confirms, never decorates",
      speed: "snappy",
      rules: ["150–250ms transitions", "Fade+2px rise only", "No parallax"],
    },
    typographyRules: {
      display: "Medium-weight grotesque, -2% tracking",
      body: "13–15px, muted foreground hierarchy",
      scale: "Restrained — hierarchy via weight and color, not size",
      rules: ["Monospace for data and labels"],
    },
    imagery: "Abstract gradients and product UI, never stock photos",
    copyDirection: "Short declarative sentences. Zero adjectives you can't defend.",
  },

  raycast: {
    id: "raycast",
    name: "Raycast",
    essence: "Keyboard-fast utility with a glowing core.",
    traits: ["compact", "fast", "glowing edges", "developer-grade"],
    heroLayout: "centered",
    navStyle: "hairline",
    density: "dense",
    layoutRules: [
      "Compact modules in tight grids",
      "Red-orange glow reserved for the primary action",
      "Dark panels on darker background, separated by luminance",
    ],
    componentRules: {
      navigation: "Tight bar with kbd-style hints",
      hero: "Bold heading + command-palette visual metaphor",
      cards: "Raised dark tiles with subtle outer glow on hover",
      buttons: "Bold, rounded-lg, saturated accent fill",
      forms: "Inline, instant-feeling, monospace accents",
    },
    motionRules: {
      character: "Snappy, springy, sub-200ms",
      speed: "snappy",
      rules: ["Spring pop on hover", "Staggered list reveals"],
    },
    typographyRules: {
      display: "Bold grotesque",
      body: "Compact with monospace metadata",
      scale: "Moderate",
      rules: ["Keyboard-key chips as a recurring motif"],
    },
    imagery: "UI screenshots and glow gradients",
    copyDirection: "Fast verbs. Feature, benefit, done.",
  },

  "arc-browser": {
    id: "arc-browser",
    name: "Arc Browser",
    essence: "Playful gradients and soft shapes with real warmth.",
    traits: ["playful", "gradient", "soft shapes", "personable"],
    heroLayout: "split",
    navStyle: "boxed",
    density: "balanced",
    layoutRules: [
      "Big rounded containers (24px+) with gradient washes",
      "Color blocks divide the page instead of hairlines",
      "Slightly irregular, hand-placed compositions",
    ],
    componentRules: {
      navigation: "Rounded container nav with a colored active pill",
      hero: "Split layout: warm statement left, vivid visual right",
      cards: "Chunky rounded tiles in alternating tints",
      buttons: "Pill-shaped, saturated, friendly",
      forms: "Rounded fields with colored focus",
    },
    motionRules: {
      character: "Bouncy and alive without being childish",
      speed: "calm",
      rules: ["Spring easing", "Color-shift hovers", "Tilt on cards"],
    },
    typographyRules: {
      display: "Rounded-feeling bold grotesque",
      body: "Friendly, larger than average",
      scale: "Generous",
      rules: ["Sentence case everywhere — never shouty caps"],
    },
    imagery: "Vivid gradients, illustrated moments",
    copyDirection: "Human, first-person, a little wit.",
  },

  vercel: {
    id: "vercel",
    name: "Vercel",
    essence: "Black, white, and typography doing all the work.",
    traits: ["monochrome", "typographic", "exact", "engineering"],
    heroLayout: "centered",
    navStyle: "hairline",
    density: "balanced",
    layoutRules: [
      "Pure black and white; gray only as hierarchy",
      "Geometry: perfect grid, visible structure",
      "Whitespace is the decoration",
    ],
    componentRules: {
      navigation: "Hairline bar, monochrome links",
      hero: "Massive tight-tracked headline, nothing else competes",
      cards: "1px bordered boxes; hover inverts",
      buttons: "White-on-black / black-on-white inversions",
      forms: "Sharp, minimal, monospace hints",
    },
    motionRules: {
      character: "Almost none — precision is the motion",
      speed: "snappy",
      rules: ["Instant state changes", "Subtle border emphasis on hover"],
    },
    typographyRules: {
      display: "Heavy grotesque, -3% tracking",
      body: "Neutral, smaller, perfectly measured",
      scale: "Dramatic display-to-body ratio",
      rules: ["Monospace for anything technical"],
    },
    imagery: "Diagrams and terminal output over photography",
    copyDirection: "Statements, not sentences.",
  },

  framer: {
    id: "framer",
    name: "Framer",
    essence: "Motion-first drama — the scroll is the story.",
    traits: ["motion-first", "dramatic", "dark", "cinematic type"],
    heroLayout: "oversized",
    navStyle: "glass-pill",
    density: "balanced",
    layoutRules: [
      "Scroll-choreographed reveals section by section",
      "Oversized type entrances",
      "Full-width dark stage with vivid accent moments",
    ],
    componentRules: {
      navigation: "Floating compact pill that condenses on scroll",
      hero: "Huge animated headline; canvas-like backdrop",
      cards: "Cards animate in as a choreographed set",
      buttons: "Rounded-xl, bold, glow on hover",
      forms: "Large fields, dramatic focus states",
    },
    motionRules: {
      character: "Choreographed, theatrical, but 60fps-disciplined",
      speed: "calm",
      rules: ["Staggered entrances", "Scroll-linked parallax", "Light sweeps on CTAs"],
    },
    typographyRules: {
      display: "Very bold, very large, tight leading",
      body: "Clean and quiet to let display breathe",
      scale: "Extreme",
      rules: ["Animate words, not letters"],
    },
    imagery: "Motion frames, gradients, dimensional renders",
    copyDirection: "Confident present tense. Short lines built to animate.",
  },

  notion: {
    id: "notion",
    name: "Notion",
    essence: "Warm paper and reading rhythm — software as a document.",
    traits: ["warm", "paper", "calm", "readable"],
    heroLayout: "editorial-left",
    navStyle: "minimal-text",
    density: "balanced",
    layoutRules: [
      "Single readable column as the spine",
      "Warm white background, soft gray panels",
      "Emoji-adjacent friendliness without clutter",
    ],
    componentRules: {
      navigation: "Plain text links, almost invisible",
      hero: "Left-aligned heading like a document title",
      cards: "Soft gray blocks with tiny radius",
      buttons: "Small, softly filled, unpretentious",
      forms: "Plain bordered fields, generous labels",
    },
    motionRules: {
      character: "Barely there — content appears, that's it",
      speed: "snappy",
      rules: ["Simple fades", "No parallax, no theatrics"],
    },
    typographyRules: {
      display: "Bold but bookish",
      body: "16px+, optimized for actual reading",
      scale: "Modest",
      rules: ["Real paragraphs welcome — this DNA can carry text"],
    },
    imagery: "Soft illustrations, candid photos",
    copyDirection: "Plain-spoken and helpful, like good documentation.",
  },

  "liquid-glass": {
    id: "liquid-glass",
    name: "Liquid Glass",
    essence: "Translucent depth — surfaces you can see through.",
    traits: ["translucent", "deep", "blurred", "luminous"],
    heroLayout: "centered",
    navStyle: "glass-pill",
    density: "balanced",
    layoutRules: [
      "Layered translucency over an ambient-lit background",
      "Hairline borders + edge-light define surfaces",
      "Accent glow bleeds through glass from behind",
    ],
    componentRules: {
      navigation: "Frosted bar with blur, hairline bottom edge",
      hero: "Centered over a radial brand glow",
      cards: "Real backdrop-blur glass with inset top light",
      buttons: "Pill, brand-filled with inner highlight",
      forms: "Glass wells, glowing focus",
    },
    motionRules: {
      character: "Smooth and liquid — eased, never abrupt",
      speed: "calm",
      rules: ["Soft rises", "Glow pulses on key actions"],
    },
    typographyRules: {
      display: "Semibold grotesque, tight",
      body: "White at opacity steps",
      scale: "Moderate-high",
      rules: ["Light text on dark glass only — contrast is sacred"],
    },
    imagery: "Reflective surfaces, lit product shots",
    copyDirection: "Modern, fluid, benefit-led.",
  },

  "contractor-pro": {
    id: "contractor-pro",
    name: "Contractor Pro",
    essence: "Job-site authority — bold, direct, impossible to misread.",
    traits: ["trust", "bold CTAs", "authority", "reviews"],
    heroLayout: "split",
    navStyle: "bold-bar",
    density: "dense",
    layoutRules: [
      "Strong horizontal bands, clear section breaks",
      "CTA visible in every viewport",
      "Trust signals (license, rating, years) repeated structurally",
      "High contrast: dark steel + safety accent",
    ],
    componentRules: {
      navigation: "Heavy bar with phone number and a hard CTA button",
      hero: "Split: blunt promise left, proof/quote form right",
      cards: "Thick-bordered tiles with bold headings",
      buttons: "Big, uppercase, saturated — built for gloved thumbs",
      forms: "Short quote forms, huge submit",
    },
    motionRules: {
      character: "Minimal — confidence doesn't wiggle",
      speed: "snappy",
      rules: ["Quick fades only", "No decorative animation"],
    },
    typographyRules: {
      display: "Extrabold condensed, uppercase",
      body: "Plain, sturdy, larger than average",
      scale: "High",
      rules: ["Numbers big: ratings, years, response times"],
    },
    imagery: "Real crews, real trucks, real job sites",
    copyDirection: "Blunt promises with proof attached. Phone number everywhere.",
  },

  "minimal-editorial": {
    id: "minimal-editorial",
    name: "Minimal Editorial",
    essence: "A magazine spread — typography first, everything else second.",
    traits: ["typography first", "magazine layout", "light", "literary"],
    heroLayout: "editorial-left",
    navStyle: "minimal-text",
    density: "airy",
    layoutRules: [
      "Asymmetric editorial grid with hanging indents",
      "Rules (thin lines) structure the page like a broadsheet",
      "Photography treated as art plates with captions",
      "Warm paper background, ink-dark text",
    ],
    componentRules: {
      navigation: "Small caps text links under a masthead",
      hero: "Left-set serif headline with a drop-cap energy; no box, no panel",
      cards: "No cards — ruled list entries with numerals",
      buttons: "Underlined text links or thin-bordered rectangles",
      forms: "Underline fields, typographic labels",
    },
    motionRules: {
      character: "Print doesn't move — near-zero motion",
      speed: "slow",
      rules: ["Slow fades only", "No transform animation"],
    },
    typographyRules: {
      display: "Light editorial serif at large optical size",
      body: "Readable serif or humanist, real line length discipline",
      scale: "Large display, classic body",
      rules: ["Italic for emphasis", "Small caps for labels", "Hang the punctuation"],
    },
    imagery: "Documentary photography, captioned like a feature story",
    copyDirection: "Written, not generated. Long-form welcome. No exclamation points.",
  },

  "startup-modern": {
    id: "startup-modern",
    name: "Startup Modern",
    essence: "Crisp light UI with confident color and obvious next steps.",
    traits: ["crisp", "light", "confident", "conversion-aware"],
    heroLayout: "centered",
    navStyle: "boxed",
    density: "balanced",
    layoutRules: [
      "Light background, elevation via soft shadows",
      "One strong brand color used decisively",
      "Benefit-led sections in predictable, scannable rhythm",
    ],
    componentRules: {
      navigation: "Clean bar with a filled CTA at the end",
      hero: "Centered promise + product proof beneath",
      cards: "White cards, soft shadow, rounded-2xl",
      buttons: "Rounded-xl solid fill with clear hover",
      forms: "Friendly, well-labeled, validation built in",
    },
    motionRules: {
      character: "Polished micro-interactions",
      speed: "snappy",
      rules: ["Soft lifts on hover", "Staggered card entrances"],
    },
    typographyRules: {
      display: "Bold geometric grotesque",
      body: "Comfortable 16px reading",
      scale: "Moderate-high",
      rules: ["Color reserved for action and emphasis"],
    },
    imagery: "Bright, real-world photos with consistent grading",
    copyDirection: "Benefit first, proof second, CTA third.",
  },

  "premium-local": {
    id: "premium-local",
    name: "Premium Local Business",
    essence: "The established local firm — warm, credentialed, trusted.",
    traits: ["trust-forward", "warm", "established", "credentialed"],
    heroLayout: "split",
    navStyle: "boxed",
    density: "balanced",
    layoutRules: [
      "Warm neutral palette with a deep heritage accent",
      "Credentials and reviews placed early and often",
      "Comfortable, familiar layout patterns — innovation isn't the point",
    ],
    componentRules: {
      navigation: "Solid bar with phone number prominent",
      hero: "Split: warm welcome + photo of real people/place",
      cards: "White panels with gentle borders",
      buttons: "Solid rounded-lg in the heritage color",
      forms: "Reassuring labels, privacy note under submit",
    },
    motionRules: {
      character: "Gentle and unhurried",
      speed: "calm",
      rules: ["Soft fades", "Nothing flashy"],
    },
    typographyRules: {
      display: "Sturdy grotesque or low-contrast serif",
      body: "Warm, readable, slightly larger",
      scale: "Moderate",
      rules: ["Established-since dates and credentials in small caps"],
    },
    imagery: "The actual team, the actual storefront, the actual work",
    copyDirection: "Neighborly and specific — names, years, places.",
  },

  "high-end-agency": {
    id: "high-end-agency",
    name: "High-End Agency",
    essence: "Art-directed restraint — oversized type and curated silence.",
    traits: ["oversized type", "art-directed", "restrained", "confident"],
    heroLayout: "oversized",
    navStyle: "minimal-text",
    density: "airy",
    layoutRules: [
      "Type IS the layout — images interrupt, not decorate",
      "Massive scale jumps between elements",
      "Horizontal rules as the only ornament",
      "Index/numbered navigation motifs",
    ],
    componentRules: {
      navigation: "Tiny monospace index links, corners of the viewport",
      hero: "Full-viewport uppercase statement, broken across lines deliberately",
      cards: "Ruled rows, not boxes — like a project index",
      buttons: "Circled arrows or underlined text — never a filled rectangle",
      forms: "Oversized single-field forms",
    },
    motionRules: {
      character: "Editorial reveals — masked text rising on scroll",
      speed: "calm",
      rules: ["Line-mask text reveals", "Slow image scale on hover"],
    },
    typographyRules: {
      display: "Ultra-large compressed uppercase",
      body: "Small, precise, wide-tracked",
      scale: "Extreme — 10x jumps welcome",
      rules: ["Numerals as graphic elements (01, 02…)"],
    },
    imagery: "Full-bleed art-directed photography, sparse",
    copyDirection: "Fragments. Confidence. Period.",
  },

  "modern-industrial": {
    id: "modern-industrial",
    name: "Modern Industrial",
    essence: "Engineering aesthetic — strong grid, steel surfaces, spec-sheet truth.",
    traits: ["strong grid", "engineering", "utilitarian", "spec-driven"],
    heroLayout: "split",
    navStyle: "bold-bar",
    density: "dense",
    layoutRules: [
      "Visible grid: sharp corners, 2px gaps, modular tiles",
      "Spec tables and stat blocks as design features",
      "Industrial accent (safety orange / steel blue) on dark graphite",
      "Diagonal hatching and measurement motifs",
    ],
    componentRules: {
      navigation: "Squared bar with mono labels, almost a toolbar",
      hero: "Split: blunt headline + stat/spec panel",
      cards: "Sharp-cornered modules with mono metadata headers",
      buttons: "Squared, uppercase, mechanical hover (no softness)",
      forms: "Grid-aligned fields with mono labels",
    },
    motionRules: {
      character: "Mechanical precision — things snap into place",
      speed: "snappy",
      rules: ["Hard-stop easing", "Counter animations on stats"],
    },
    typographyRules: {
      display: "Extrabold grotesque, tight, occasionally uppercase",
      body: "Utilitarian with monospace technical data",
      scale: "High",
      rules: ["Units and numbers in mono: PSI, mil, years"],
    },
    imagery: "Process shots, machinery, surface textures",
    copyDirection: "Spec-sheet honesty. Numbers beat adjectives.",
  },
};

export function getDesignDNA(id: DesignSystemId): DesignDNA {
  return DNA[id] ?? DNA["liquid-glass"];
}

export const DESIGN_DNA = DNA;
